### ISSUE TITLE
Automatic builds of bundles?

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_bundle_lib#1]
We're trying to move from Jenkins, perhaps to Travis. What would that look like here?
- Do we need the whole virtual machine, or is there something lighter we could do?
- If we do need the VM, can Travis caching save us the time to build the VM each time? But making sure the cache is invalidated correctly could be hard.
- I don't think we have a hook for "after-the-PR-is-merged", unless we want to rely on a daily cron to check if the version number has been incremented? Or maybe we do push the latest version with each PR... if the PR needs tweaks, then we push again, and clobber that version on S3? ie, versions are not considered stable until some later formal release? That does not sound like a good policy to me.
- Or maybe it does push to S3, but not to the final local: If the build is good, that step is left to a human?
- If this did sound like something worth pursuing, could someone with admin rights turn on travis for this repo at https://travis-ci.org/profile/Caleydo? I can't.
- and what are the artifacts we need at the end of the pipe?
  - js
  - zipped js
  - css?
  - generated docs? ... but maybe these should be done per module instead? Otherwise, if we have the same module in multiple bundles, there will be redundant documentation out there, and that could be confusing...
- Whatever we do here, do we do the same thing for all the other bundles?

**Comment by mstreit** [comment]
I've turned on Travis for this repo. Let's discuss the rest today after the Caleydo meeting.

**Comment by mccalluc** [comment]
(Decided that this is stretching Travis too far: it can't watch dependencies. Will continue with Jenkins, I think. Closing.)

**Comment by mccalluc** [comment]
Sorry: Better to keep this open: it's just about getting the job done, not about Travis in particular.

**Comment by sgratzl** [comment]
You don't need the whole virtual machine, building is just about compiling Typescript and bundling them together. So node+bower+grunt at the moment. using `./manage.sh resolve_dev` just resolves the typescript definitions and skips python and other stuff.

**Comment by mccalluc** [comment]
@thinkh : Following up from Slack from Thursday: My immediate goal is to build web bundle. (I hope that might help me think about building single repos, but that might be hoping too much.)
- Scanning http://dev.caleydo.org/jenkins/ I do not see an item that creates an artifact like "web_bundle"
- package.json here does not list clue: so this is not what builds web_bundle? Or we have not rebuilt web_bundle recently? But isn't that what Jenkins should be doing for us?
- sgratzl suggests that I shouldn't need the whole vm for this, but I have not succeeded in building it locally. I think there are steps elided in the readme.

```
npm install -g browserify
npm install grunt --save-dev
npm install
#npm WARN bundle_lib@0.0.1 requires a peer of caleydo_core@* but none was installed.
#npm WARN bundle_lib@0.0.1 requires a peer of caleydo_d3@* but none was installed.
#npm WARN bundle_lib@0.0.1 requires a peer of caleydo_vis@* but none was installed.
#npm WARN bundle_lib@0.0.1 requires a peer of caleydo_vis_lineup@* but none was installed.
# Should something else work?
npm install caleydo/caleydo_core
npm install caleydo/caleydo_d3
npm install caleydo/caleydo_vis
npm install caleydo/caleydo_vis
npm install caleydo/caleydo_vis_lineup
# Need to pin versions, but is there something else I can do to get them installed from package.json?
grunt build:lib
# Fatal error: Unable to find Gruntfile.
```

What I want at the end is a sequence of steps that I could put in travis.yml which would produce a valid bundle which we could run a couple end-to-end tests on.

**Comment by mccalluc** [comment]
@thinkh: Repeating the point above, web_bundle includes CLUE, and judging by https://github.com/Caleydo/bundle_lib/blob/master/package.json#L9 this does not. I'm misunderstanding something?

**Comment by mccalluc** [comment]
@thinkh / @sgratzl: To get this built on travis, I envision...
- Making a tag of v0.0.1 for https://github.com/Caleydo/caleydo_web_container
- `cd ..` and then do a `--depth 1` checkout of caleydo_web_container at that tag
- symlink bundle_lib under ../caleydo_web_container/plugins
- My understanding is that the vm is most important for keeping a clean workspace? On travis, that is not necessary, and building the vm from scratch with every push would be painfully slow.
- So next just `./manage.sh resolve`
- npm install grunt
- grunt compile_products

If that seems reasonable, please let me know.

**Comment by sgratzl** [comment]
notes: 
- instead of `./manage.sh resolve` `./manage.sh resolve_dev` then it will just installs the compile dependencies but skips all the pythn stuff. 
- `npm install -g grunt tsd` before the resolve step
- `grunt --jenkins` ... will build everything and report in a more console friendly way

**Comment by sgratzl** [comment]
see also e.g. the jenkins job caleydo_web_daily and its configuration

**Comment by sgratzl** [comment]
regading clue: you are right. of clue just the provenance infrastructure is part of the core. However, not the associated visualizations.

**Comment by mccalluc** [comment]
@sgratzl: Thanks! Status update, which I'll probably update again before I leave today, and before you begin tomorrow.
- Running locally I hit this error:

```
caleydo_web_container$ bash manage.sh resolve_dev
--- resolving dev dependencies ---
manage.sh: line 130: node_modules/.bin/caleydo: No such file or directory
```
- `caleydo_web_daily` has not succeeded in 29 days... so even if I understood exactly what it did, I'd be surprised if were to work for me.

Regarding CLUE, I think there's ambiguity around what we want, and around what the software we have right now should be doing:
- My sense is that Nils at least thinks more of CLUE should be in core... For myself, I think it might be better to make a subset of the functionality really solid... and you guys might have still another opinion.
- The string "clue" occurs precisely once in https://s3.amazonaws.com/caleydo-releases/v0.0.1/caleydo.js. Does that match your expectations?

```
var LocalStorageProvenanceGraphManager = function () {
        function LocalStorageProvenanceGraphManager(options) {
            if (options === void 0) {
                options = {};
            }
            this.options = {
                storage: localStorage,
                prefix: 'clue',
                application: 'unknown'
            };
            C.mixin(this.options, options);
        }
```

**Comment by mccalluc** [comment]
Using travis deploy, release v0.0.1 is in place on github. Closing.
