### ISSUE TITLE
Built JS contains illegal characters

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_bundle_lib#4]
`npm run build` seems to work. I then tried this:
```html
<!DOCTYPE html>
<html>
  <body>
    <script src="build/phovea_bundle_lib.js"></script>
  </body>
</html>
```
The javascript doesn't load because it hits illegal characters in this line:
```
var Îµ = 1e-6, Îµ2 = Îµ * Îµ, Ï€ = Math.PI, Ï„ = 2 * Ï€, Ï„Îµ = Ï„ - Îµ, halfÏ€ = Ï€ / 2, d3_radians = Ï€ / 180, d3_degrees = 180 / Ï€;
```
If the character encoding issue were resolved, this might work, but it's safer to keep the JS to ASCII. I'll see if I can track this down in the dependencies. End goal is to have an automated test load the compiled JS, and at least make sure the appropriate global is available.

**Comment by mccalluc** [comment]
It's coming from D3. [Here's](https://github.com/d3/d3/search?q=%221e-6%22) a note about the issue: "To the consternation of some users, 3.x employed Unicode variable names such as λ, φ, τ and π for a concise representation of mathematical operations. A downside of this approach was that a SyntaxError would occur if you loaded the non-minified D3 using ISO-8859-1 instead of UTF-8. 3.x also used Unicode string literals, such as the SI-prefix µ for 1e-6. 4.0 uses only ASCII variable names and ASCII string literals"

Options:
- Upgrade d3
- Don't bundle d3
- As a stop-gap, but not for the long term, declaring encoding explicitly works:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <script src="build/phovea_bundle_lib.js"></script>
  </body>
</html>
```

**Comment by sgratzl** [comment]
> Upgrade d3

to v4? because phovea is using the latest v3

> Don't bundle d3

if we don't bundle d3, we shouldn't bundle other libraries either

> As a stop-gap, but not for the long term, declaring encoding explicitly works:

why is a short term solution, people should use utf-8 all the time?

**Comment by mccalluc** [comment]
- It would have to be to v4, and that's too big a change.
- If we didn't bundle d3, then folks would have to include it themselves, which would be another thing to go wrong.
- People should use utf-8, but people aren't perfect. We can try to minimize roadblocks.

Maybe it would be possible to replace the charcters with `\u` encodings, so the whole thing is ASCII?

``` javascript
var \u0061 = 'hello world?';
console.log(a);
// hello world?
```

Low priority.

**Comment by sgratzl** [comment]
I'm not gonna hack the d3 library. If you find a webpack2 plugin that does that, maybe
