### ISSUE TITLE
Deploy built JS to S3

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_bundle_lib#6]
Tagged releases are automatically being built and stored back on Github by Travis. (yay!) We should add a second deploy section to store on s3 (because web pages can't just use github as a CDN, I think because the mime types are wrong).

@ngehlenborg or @mstreit : https://s3.amazonaws.com/caleydo-releases/ exists: Should there be a new `phovea-releases` bucket? Or a subdirectory in the existing? Either way is fine. We'll want to put encrypted credentials in travis.yml.

https://docs.travis-ci.com/user/deployment/s3/

**Comment by sgratzl** [comment]
see also Caleydo/lineup.js#125

**Comment by mstreit** [comment]
For me both is fine, but I don't see a problem with using the same bucket.

**Comment by mccalluc** [comment]
@sgratzl: The `dist` directory is something that we create only in the tag branch, rather than something that github is providing for us automatically, right? I think that could work, but I'm concerned about requiring extra steps in the tag release process, and to a lesser extent, I worry about someone starting from a tag, not completely refreshing dist, and then releasing another tag, where the source code and the compiled code are not in sync.

I do think that the tag release project should be consistent across projects, whatever it is.

Maybe travis should do a fresh compile and make sure dist is in sync? Apologies if I'm missing something obvious.

@mstreit: Your thoughts on the above? If you do prefer S3, I'm not sure that I ever got an account in the Caleydo AWS group: I've only been using refinery.

**Comment by mstreit** [comment]
AWS sounds good to me. If there is a better option, I'm fine with that, too.
@thinkh, could you send @mccalluc the Caleydo AWS credentials, please?
